import { test } from "vitest";
import { rotateCard } from "../Tableturf";
import { TestUtil } from "./TestUtil";
import { rectToString } from "../Utils";

test("rotate_0", () => {
  const actual = rotateCard(TestUtil.card.Nautilus, 0);
  TestUtil.expectRectEqual(actual, rectToString(TestUtil.card.Nautilus));
});

test("rotate_1", () => {
  const actual = rotateCard(TestUtil.card.Nautilus, 1);
  TestUtil.expectRectEqual(
    actual,
    `
    ........
    ...aaa..
    ...aaa..
    ...a....
    ...a....
    ...A....
    ........
    ........
    `
  );
});

test("rotate_2", () => {
  const actual = rotateCard(TestUtil.card.Nautilus, 2);
  TestUtil.expectRectEqual(
    actual,
    `
    ........
    ........
    ........
    ..Aaaaa.
    .....aa.
    .....aa.
    ........
    ........
    `
  );
});

test("rotate_3", () => {
  const actual = rotateCard(TestUtil.card.Nautilus, 3);
  TestUtil.expectRectEqual(
    actual,
    `
    ........
    ........
    ....A...
    ....a...
    ....a...
    ..aaa...
    ..aaa...
    ........
    `
  );
});
